name: Test
on: [push]
jobs:
  test:
    name: Test
    strategy:
      matrix:
        include:
          - os: windows-latest
            node_version: current
          - os: macos-latest
            node_version: lts/*
          - os: ubuntu-latest
            node_version: lts/*
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1.0.0
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node_version }}
    - run: npm i
    - run: npm run build
    - run: npm test
