name: Test
on: [push]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: ["lts/*", "current"]
    steps:
    - uses: actions/checkout@v1.0.0
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node_version }}
    - run: npm i
    - run: npm run build
    - run: npm test
